// Mocks generated by Mockito 5.4.2 from annotations
// in app_center/test/appstream_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:appstream/src/component.dart' as _i3;
import 'package:appstream/src/pool.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AppstreamPool].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppstreamPool extends _i1.Mock implements _i2.AppstreamPool {
  MockAppstreamPool() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.AppstreamComponent> get components => (super.noSuchMethod(
        Invocation.getter(#components),
        returnValue: <_i3.AppstreamComponent>[],
      ) as List<_i3.AppstreamComponent>);
  @override
  _i4.Future<void> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
