// Mocks generated by Mockito 5.4.2 from annotations
// in app_center/test/test_utils.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:app_center/snapd.dart' as _i4;
import 'package:app_center/src/manage/manage_model.dart' as _i9;
import 'package:dbus/dbus.dart' as _i12;
import 'package:file/file.dart' as _i10;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i5;
import 'package:gtk/src/gtk_application_notifier.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:packagekit/src/packagekit_client.dart' as _i6;
import 'package:snapcraft_launcher/snapcraft_launcher.dart' as _i3;
import 'package:snapd/snapd.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSnap_0 extends _i1.SmartFake implements _i2.Snap {
  _FakeSnap_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePrivilegedDesktopLauncher_1 extends _i1.SmartFake
    implements _i3.PrivilegedDesktopLauncher {
  _FakePrivilegedDesktopLauncher_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSnapdService_2 extends _i1.SmartFake implements _i4.SnapdService {
  _FakeSnapdService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAsyncValue_3<T> extends _i1.SmartFake implements _i5.AsyncValue<T> {
  _FakeAsyncValue_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdatesModel_4 extends _i1.SmartFake implements _i4.UpdatesModel {
  _FakeUpdatesModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSnapdSystemInfoResponse_5 extends _i1.SmartFake
    implements _i2.SnapdSystemInfoResponse {
  _FakeSnapdSystemInfoResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSnapdConnectionsResponse_6 extends _i1.SmartFake
    implements _i2.SnapdConnectionsResponse {
  _FakeSnapdConnectionsResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSnapdLoginResponse_7 extends _i1.SmartFake
    implements _i2.SnapdLoginResponse {
  _FakeSnapdLoginResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSnapdChange_8 extends _i1.SmartFake implements _i2.SnapdChange {
  _FakeSnapdChange_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePackageKitTransaction_9 extends _i1.SmartFake
    implements _i6.PackageKitTransaction {
  _FakePackageKitTransaction_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SnapLauncher].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnapLauncher extends _i1.Mock implements _i4.SnapLauncher {
  MockSnapLauncher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Snap get snap => (super.noSuchMethod(
        Invocation.getter(#snap),
        returnValue: _FakeSnap_0(
          this,
          Invocation.getter(#snap),
        ),
      ) as _i2.Snap);
  @override
  _i3.PrivilegedDesktopLauncher get launcher => (super.noSuchMethod(
        Invocation.getter(#launcher),
        returnValue: _FakePrivilegedDesktopLauncher_1(
          this,
          Invocation.getter(#launcher),
        ),
      ) as _i3.PrivilegedDesktopLauncher);
  @override
  bool get isLaunchable => (super.noSuchMethod(
        Invocation.getter(#isLaunchable),
        returnValue: false,
      ) as bool);
  @override
  void open() => super.noSuchMethod(
        Invocation.method(
          #open,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SnapModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnapModel extends _i1.Mock implements _i4.SnapModel {
  MockSnapModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SnapdService get snapd => (super.noSuchMethod(
        Invocation.getter(#snapd),
        returnValue: _FakeSnapdService_2(
          this,
          Invocation.getter(#snapd),
        ),
      ) as _i4.SnapdService);
  @override
  String get snapName => (super.noSuchMethod(
        Invocation.getter(#snapName),
        returnValue: '',
      ) as String);
  @override
  set localSnap(_i2.Snap? _localSnap) => super.noSuchMethod(
        Invocation.setter(
          #localSnap,
          _localSnap,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set storeSnap(_i2.Snap? _storeSnap) => super.noSuchMethod(
        Invocation.setter(
          #storeSnap,
          _storeSnap,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.AsyncValue<void> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_3<void>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.AsyncValue<void>);
  @override
  _i2.Snap get snap => (super.noSuchMethod(
        Invocation.getter(#snap),
        returnValue: _FakeSnap_0(
          this,
          Invocation.getter(#snap),
        ),
      ) as _i2.Snap);
  @override
  bool get isInstalled => (super.noSuchMethod(
        Invocation.getter(#isInstalled),
        returnValue: false,
      ) as bool);
  @override
  bool get hasGallery => (super.noSuchMethod(
        Invocation.getter(#hasGallery),
        returnValue: false,
      ) as bool);
  @override
  set selectedChannel(String? channel) => super.noSuchMethod(
        Invocation.setter(
          #selectedChannel,
          channel,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> cancel() => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> install() => (super.noSuchMethod(
        Invocation.method(
          #install,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> remove() => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ManageModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockManageModel extends _i1.Mock implements _i9.ManageModel {
  MockManageModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SnapdService get snapd => (super.noSuchMethod(
        Invocation.getter(#snapd),
        returnValue: _FakeSnapdService_2(
          this,
          Invocation.getter(#snapd),
        ),
      ) as _i4.SnapdService);
  @override
  _i4.UpdatesModel get updatesModel => (super.noSuchMethod(
        Invocation.getter(#updatesModel),
        returnValue: _FakeUpdatesModel_4(
          this,
          Invocation.getter(#updatesModel),
        ),
      ) as _i4.UpdatesModel);
  @override
  _i5.AsyncValue<void> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_3<void>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.AsyncValue<void>);
  @override
  Iterable<_i2.Snap> get refreshableSnaps => (super.noSuchMethod(
        Invocation.getter(#refreshableSnaps),
        returnValue: <_i2.Snap>[],
      ) as Iterable<_i2.Snap>);
  @override
  Iterable<_i2.Snap> get nonRefreshableSnaps => (super.noSuchMethod(
        Invocation.getter(#nonRefreshableSnaps),
        returnValue: <_i2.Snap>[],
      ) as Iterable<_i2.Snap>);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SnapdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnapdService extends _i1.Mock implements _i4.SnapdService {
  MockSnapdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get allowInteraction => (super.noSuchMethod(
        Invocation.getter(#allowInteraction),
        returnValue: false,
      ) as bool);
  @override
  set allowInteraction(bool? _allowInteraction) => super.noSuchMethod(
        Invocation.setter(
          #allowInteraction,
          _allowInteraction,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set userAgent(String? value) => super.noSuchMethod(
        Invocation.setter(
          #userAgent,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.Future<void> waitChange(String? changeId) => (super.noSuchMethod(
        Invocation.method(
          #waitChange,
          [changeId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> loadAuthorization({String? path}) => (super.noSuchMethod(
        Invocation.method(
          #loadAuthorization,
          [],
          {#path: path},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  void setAuthorization(
    String? macaroon,
    List<String>? discharges,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAuthorization,
          [
            macaroon,
            discharges,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.Future<_i2.SnapdSystemInfoResponse> systemInfo() => (super.noSuchMethod(
        Invocation.method(
          #systemInfo,
          [],
        ),
        returnValue: _i7.Future<_i2.SnapdSystemInfoResponse>.value(
            _FakeSnapdSystemInfoResponse_5(
          this,
          Invocation.method(
            #systemInfo,
            [],
          ),
        )),
      ) as _i7.Future<_i2.SnapdSystemInfoResponse>);
  @override
  _i7.Future<List<_i2.Snap>> getSnaps() => (super.noSuchMethod(
        Invocation.method(
          #getSnaps,
          [],
        ),
        returnValue: _i7.Future<List<_i2.Snap>>.value(<_i2.Snap>[]),
      ) as _i7.Future<List<_i2.Snap>>);
  @override
  _i7.Future<_i2.Snap> getSnap(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getSnap,
          [name],
        ),
        returnValue: _i7.Future<_i2.Snap>.value(_FakeSnap_0(
          this,
          Invocation.method(
            #getSnap,
            [name],
          ),
        )),
      ) as _i7.Future<_i2.Snap>);
  @override
  _i7.Future<List<_i2.SnapApp>> getApps({
    List<String>? names,
    _i2.SnapdAppFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApps,
          [],
          {
            #names: names,
            #filter: filter,
          },
        ),
        returnValue: _i7.Future<List<_i2.SnapApp>>.value(<_i2.SnapApp>[]),
      ) as _i7.Future<List<_i2.SnapApp>>);
  @override
  _i7.Future<List<_i2.SnapdCategoryDetails>> getCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i7.Future<List<_i2.SnapdCategoryDetails>>.value(
            <_i2.SnapdCategoryDetails>[]),
      ) as _i7.Future<List<_i2.SnapdCategoryDetails>>);
  @override
  _i7.Future<_i2.SnapdConnectionsResponse> getConnections({
    String? snap,
    String? interface,
    _i2.SnapdConnectionFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConnections,
          [],
          {
            #snap: snap,
            #interface: interface,
            #filter: filter,
          },
        ),
        returnValue: _i7.Future<_i2.SnapdConnectionsResponse>.value(
            _FakeSnapdConnectionsResponse_6(
          this,
          Invocation.method(
            #getConnections,
            [],
            {
              #snap: snap,
              #interface: interface,
              #filter: filter,
            },
          ),
        )),
      ) as _i7.Future<_i2.SnapdConnectionsResponse>);
  @override
  _i7.Future<String> refreshMany(List<String>? names) => (super.noSuchMethod(
        Invocation.method(
          #refreshMany,
          [names],
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> connect(
    String? snap,
    String? plug,
    String? slotSnap,
    String? slot,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [
            snap,
            plug,
            slotSnap,
            slot,
          ],
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> disconnect(
    String? plugSnap,
    String? plug,
    String? slotSnap,
    String? slot,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [
            plugSnap,
            plug,
            slotSnap,
            slot,
          ],
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<List<_i2.Snap>> find({
    String? query,
    String? name,
    String? category,
    String? section,
    _i2.SnapFindFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #find,
          [],
          {
            #query: query,
            #name: name,
            #category: category,
            #section: section,
            #filter: filter,
          },
        ),
        returnValue: _i7.Future<List<_i2.Snap>>.value(<_i2.Snap>[]),
      ) as _i7.Future<List<_i2.Snap>>);
  @override
  _i7.Future<_i2.SnapdLoginResponse> login(
    String? email,
    String? password, {
    String? otp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
          {#otp: otp},
        ),
        returnValue:
            _i7.Future<_i2.SnapdLoginResponse>.value(_FakeSnapdLoginResponse_7(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
            {#otp: otp},
          ),
        )),
      ) as _i7.Future<_i2.SnapdLoginResponse>);
  @override
  _i7.Future<dynamic> logout(int? id) => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [id],
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);
  @override
  _i7.Future<String> install(
    String? name, {
    String? channel,
    String? revision,
    bool? classic = false,
    bool? dangerous = false,
    bool? devmode = false,
    bool? jailmode = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #install,
          [name],
          {
            #channel: channel,
            #revision: revision,
            #classic: classic,
            #dangerous: dangerous,
            #devmode: devmode,
            #jailmode: jailmode,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> refresh(
    String? name, {
    String? channel,
    bool? classic = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [name],
          {
            #channel: channel,
            #classic: classic,
          },
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> remove(
    String? name, {
    bool? purge = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [name],
          {#purge: purge},
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> enable(String? name) => (super.noSuchMethod(
        Invocation.method(
          #enable,
          [name],
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<String> disable(String? name) => (super.noSuchMethod(
        Invocation.method(
          #disable,
          [name],
        ),
        returnValue: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<_i2.SnapdChange> getChange(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getChange,
          [id],
        ),
        returnValue: _i7.Future<_i2.SnapdChange>.value(_FakeSnapdChange_8(
          this,
          Invocation.method(
            #getChange,
            [id],
          ),
        )),
      ) as _i7.Future<_i2.SnapdChange>);
  @override
  _i7.Future<List<_i2.SnapdChange>> getChanges({
    _i2.SnapdChangeFilter? filter,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChanges,
          [],
          {
            #filter: filter,
            #name: name,
          },
        ),
        returnValue:
            _i7.Future<List<_i2.SnapdChange>>.value(<_i2.SnapdChange>[]),
      ) as _i7.Future<List<_i2.SnapdChange>>);
  @override
  _i7.Future<_i2.SnapdChange> abortChange(String? id) => (super.noSuchMethod(
        Invocation.method(
          #abortChange,
          [id],
        ),
        returnValue: _i7.Future<_i2.SnapdChange>.value(_FakeSnapdChange_8(
          this,
          Invocation.method(
            #abortChange,
            [id],
          ),
        )),
      ) as _i7.Future<_i2.SnapdChange>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.Stream<List<_i2.Snap>> getCategory(
    String? name, {
    Duration? expiry = const Duration(days: 1),
    _i10.FileSystem? fs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategory,
          [name],
          {
            #expiry: expiry,
            #fs: fs,
          },
        ),
        returnValue: _i7.Stream<List<_i2.Snap>>.empty(),
      ) as _i7.Stream<List<_i2.Snap>>);
  @override
  _i7.Stream<_i2.Snap?> getStoreSnap(
    String? name, {
    Duration? expiry = const Duration(minutes: 1),
    _i10.FileSystem? fs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStoreSnap,
          [name],
          {
            #expiry: expiry,
            #fs: fs,
          },
        ),
        returnValue: _i7.Stream<_i2.Snap?>.empty(),
      ) as _i7.Stream<_i2.Snap?>);
  @override
  _i7.Stream<List<_i2.Snap>> getStoreSnaps(
    List<String>? names, {
    Duration? expiry = const Duration(minutes: 1),
    _i10.FileSystem? fs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStoreSnaps,
          [names],
          {
            #expiry: expiry,
            #fs: fs,
          },
        ),
        returnValue: _i7.Stream<List<_i2.Snap>>.empty(),
      ) as _i7.Stream<List<_i2.Snap>>);
  @override
  _i7.Stream<_i2.SnapdChange> watchChange(
    String? id, {
    Duration? interval = const Duration(milliseconds: 100),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchChange,
          [id],
          {#interval: interval},
        ),
        returnValue: _i7.Stream<_i2.SnapdChange>.empty(),
      ) as _i7.Stream<_i2.SnapdChange>);
  @override
  _i7.Stream<List<String>> watchChanges({
    String? name,
    Duration? interval = const Duration(milliseconds: 100),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchChanges,
          [],
          {
            #name: name,
            #interval: interval,
          },
        ),
        returnValue: _i7.Stream<List<String>>.empty(),
      ) as _i7.Stream<List<String>>);
}

/// A class which mocks [UpdatesModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatesModel extends _i1.Mock implements _i4.UpdatesModel {
  MockUpdatesModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SnapdService get snapd => (super.noSuchMethod(
        Invocation.getter(#snapd),
        returnValue: _FakeSnapdService_2(
          this,
          Invocation.getter(#snapd),
        ),
      ) as _i4.SnapdService);
  @override
  Iterable<String> get refreshableSnapNames => (super.noSuchMethod(
        Invocation.getter(#refreshableSnapNames),
        returnValue: <String>[],
      ) as Iterable<String>);
  @override
  _i5.AsyncValue<void> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_3<void>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.AsyncValue<void>);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i7.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  bool hasUpdate(String? snapName) => (super.noSuchMethod(
        Invocation.method(
          #hasUpdate,
          [snapName],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i7.Future<void> updateAll() => (super.noSuchMethod(
        Invocation.method(
          #updateAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GtkApplicationNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockGtkApplicationNotifier extends _i1.Mock
    implements _i11.GtkApplicationNotifier {
  MockGtkApplicationNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addCommandLineListener(_i11.GtkCommandLineListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addCommandLineListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeCommandLineListener(_i11.GtkCommandLineListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeCommandLineListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addOpenListener(_i11.GtkOpenListener? listener) => super.noSuchMethod(
        Invocation.method(
          #addOpenListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeOpenListener(_i11.GtkOpenListener? listener) => super.noSuchMethod(
        Invocation.method(
          #removeOpenListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyCommandLine(List<String>? args) => super.noSuchMethod(
        Invocation.method(
          #notifyCommandLine,
          [args],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyOpen({
    required List<String>? files,
    required String? hint,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #notifyOpen,
          [],
          {
            #files: files,
            #hint: hint,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PackageKitClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackageKitClient extends _i1.Mock implements _i6.PackageKitClient {
  MockPackageKitClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set locale(String? _locale) => super.noSuchMethod(
        Invocation.setter(
          #locale,
          _locale,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get background => (super.noSuchMethod(
        Invocation.getter(#background),
        returnValue: false,
      ) as bool);
  @override
  set background(bool? _background) => super.noSuchMethod(
        Invocation.setter(
          #background,
          _background,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get interactive => (super.noSuchMethod(
        Invocation.getter(#interactive),
        returnValue: false,
      ) as bool);
  @override
  set interactive(bool? _interactive) => super.noSuchMethod(
        Invocation.setter(
          #interactive,
          _interactive,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get idle => (super.noSuchMethod(
        Invocation.getter(#idle),
        returnValue: false,
      ) as bool);
  @override
  set idle(bool? _idle) => super.noSuchMethod(
        Invocation.setter(
          #idle,
          _idle,
        ),
        returnValueForMissingStub: null,
      );
  @override
  int get cacheAge => (super.noSuchMethod(
        Invocation.getter(#cacheAge),
        returnValue: 0,
      ) as int);
  @override
  set cacheAge(int? _cacheAge) => super.noSuchMethod(
        Invocation.setter(
          #cacheAge,
          _cacheAge,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get backendAuthor => (super.noSuchMethod(
        Invocation.getter(#backendAuthor),
        returnValue: '',
      ) as String);
  @override
  String get backendDescription => (super.noSuchMethod(
        Invocation.getter(#backendDescription),
        returnValue: '',
      ) as String);
  @override
  String get backendName => (super.noSuchMethod(
        Invocation.getter(#backendName),
        returnValue: '',
      ) as String);
  @override
  String get distroId => (super.noSuchMethod(
        Invocation.getter(#distroId),
        returnValue: '',
      ) as String);
  @override
  Set<_i6.PackageKitFilter> get filters => (super.noSuchMethod(
        Invocation.getter(#filters),
        returnValue: <_i6.PackageKitFilter>{},
      ) as Set<_i6.PackageKitFilter>);
  @override
  Set<_i6.PackageKitGroup> get groups => (super.noSuchMethod(
        Invocation.getter(#groups),
        returnValue: <_i6.PackageKitGroup>{},
      ) as Set<_i6.PackageKitGroup>);
  @override
  bool get locked => (super.noSuchMethod(
        Invocation.getter(#locked),
        returnValue: false,
      ) as bool);
  @override
  List<String> get mimeTypes => (super.noSuchMethod(
        Invocation.getter(#mimeTypes),
        returnValue: <String>[],
      ) as List<String>);
  @override
  Set<_i6.PackageKitRole> get roles => (super.noSuchMethod(
        Invocation.getter(#roles),
        returnValue: <_i6.PackageKitRole>{},
      ) as Set<_i6.PackageKitRole>);
  @override
  _i6.PackageKitNetworkState get networkState => (super.noSuchMethod(
        Invocation.getter(#networkState),
        returnValue: _i6.PackageKitNetworkState.unknown,
      ) as _i6.PackageKitNetworkState);
  @override
  int get versionMajor => (super.noSuchMethod(
        Invocation.getter(#versionMajor),
        returnValue: 0,
      ) as int);
  @override
  int get versionMinor => (super.noSuchMethod(
        Invocation.getter(#versionMinor),
        returnValue: 0,
      ) as int);
  @override
  int get versionMicro => (super.noSuchMethod(
        Invocation.getter(#versionMicro),
        returnValue: 0,
      ) as int);
  @override
  _i7.Stream<List<String>> get propertiesChanged => (super.noSuchMethod(
        Invocation.getter(#propertiesChanged),
        returnValue: _i7.Stream<List<String>>.empty(),
      ) as _i7.Stream<List<String>>);
  @override
  _i7.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<_i6.PackageKitTransaction> getTransaction(
          _i12.DBusObjectPath? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransaction,
          [path],
        ),
        returnValue: _i7.Future<_i6.PackageKitTransaction>.value(
            _FakePackageKitTransaction_9(
          this,
          Invocation.method(
            #getTransaction,
            [path],
          ),
        )),
      ) as _i7.Future<_i6.PackageKitTransaction>);
  @override
  _i7.Future<_i6.PackageKitTransaction> createTransaction() =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransaction,
          [],
        ),
        returnValue: _i7.Future<_i6.PackageKitTransaction>.value(
            _FakePackageKitTransaction_9(
          this,
          Invocation.method(
            #createTransaction,
            [],
          ),
        )),
      ) as _i7.Future<_i6.PackageKitTransaction>);
  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [PackageKitTransaction].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackageKitTransaction extends _i1.Mock
    implements _i6.PackageKitTransaction {
  MockPackageKitTransaction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i6.PackageKitEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _i7.Stream<_i6.PackageKitEvent>.empty(),
      ) as _i7.Stream<_i6.PackageKitEvent>);
  @override
  set events(_i7.Stream<_i6.PackageKitEvent>? _events) => super.noSuchMethod(
        Invocation.setter(
          #events,
          _events,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.PackageKitRole get role => (super.noSuchMethod(
        Invocation.getter(#role),
        returnValue: _i6.PackageKitRole.unknown,
      ) as _i6.PackageKitRole);
  @override
  _i6.PackageKitStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i6.PackageKitStatus.unknown,
      ) as _i6.PackageKitStatus);
  @override
  String get lastPackage => (super.noSuchMethod(
        Invocation.getter(#lastPackage),
        returnValue: '',
      ) as String);
  @override
  int get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: 0,
      ) as int);
  @override
  int get percentage => (super.noSuchMethod(
        Invocation.getter(#percentage),
        returnValue: 0,
      ) as int);
  @override
  bool get allowCancel => (super.noSuchMethod(
        Invocation.getter(#allowCancel),
        returnValue: false,
      ) as bool);
  @override
  bool get callerActive => (super.noSuchMethod(
        Invocation.getter(#callerActive),
        returnValue: false,
      ) as bool);
  @override
  int get elapsedTime => (super.noSuchMethod(
        Invocation.getter(#elapsedTime),
        returnValue: 0,
      ) as int);
  @override
  int get remainingTime => (super.noSuchMethod(
        Invocation.getter(#remainingTime),
        returnValue: 0,
      ) as int);
  @override
  int get speed => (super.noSuchMethod(
        Invocation.getter(#speed),
        returnValue: 0,
      ) as int);
  @override
  int get downloadSizeRemaining => (super.noSuchMethod(
        Invocation.getter(#downloadSizeRemaining),
        returnValue: 0,
      ) as int);
  @override
  Set<_i6.PackageKitTransactionFlag> get transactionFlags =>
      (super.noSuchMethod(
        Invocation.getter(#transactionFlags),
        returnValue: <_i6.PackageKitTransactionFlag>{},
      ) as Set<_i6.PackageKitTransactionFlag>);
  @override
  _i7.Stream<List<String>> get propertiesChanged => (super.noSuchMethod(
        Invocation.getter(#propertiesChanged),
        returnValue: _i7.Stream<List<String>>.empty(),
      ) as _i7.Stream<List<String>>);
  @override
  _i7.Future<void> cancel() => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> dependsOn(
    Iterable<_i6.PackageKitPackageId>? packageIds, {
    Set<_i6.PackageKitFilter>? filter = const {},
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dependsOn,
          [packageIds],
          {
            #filter: filter,
            #recursive: recursive,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> getDetails(Iterable<_i6.PackageKitPackageId>? packageIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetails,
          [packageIds],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> getDetailsLocal(Iterable<String>? paths) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailsLocal,
          [paths],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> downloadPackages(
    Iterable<_i6.PackageKitPackageId>? packageIds, {
    bool? storeInCache = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadPackages,
          [packageIds],
          {#storeInCache: storeInCache},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> getFiles(Iterable<_i6.PackageKitPackageId>? packageIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFiles,
          [packageIds],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> getFilesLocal(Iterable<String>? paths) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilesLocal,
          [paths],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> getPackages(
          {Set<_i6.PackageKitFilter>? filter = const {}}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackages,
          [],
          {#filter: filter},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> getRepositoryList(
          {Set<_i6.PackageKitFilter>? filter = const {}}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRepositoryList,
          [],
          {#filter: filter},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> setRepositoryEnabled(
    String? id,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRepositoryEnabled,
          [
            id,
            enabled,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> setRepositoryData(
    String? id,
    String? parameter,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRepositoryData,
          [
            id,
            parameter,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> removeRepository(
    String? id, {
    bool? autoremovePackages = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRepository,
          [id],
          {#autoremovePackages: autoremovePackages},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> getUpdateDetail(
          Iterable<_i6.PackageKitPackageId>? packageIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpdateDetail,
          [packageIds],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> getUpdates({Set<_i6.PackageKitFilter>? filter = const {}}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpdates,
          [],
          {#filter: filter},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> installFiles(
    Iterable<String>? paths, {
    Set<_i6.PackageKitTransactionFlag>? transactionFlags = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #installFiles,
          [paths],
          {#transactionFlags: transactionFlags},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> installPackages(
    Iterable<_i6.PackageKitPackageId>? packageIds, {
    Set<_i6.PackageKitTransactionFlag>? transactionFlags = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #installPackages,
          [packageIds],
          {#transactionFlags: transactionFlags},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> refreshCache({bool? force = false}) => (super.noSuchMethod(
        Invocation.method(
          #refreshCache,
          [],
          {#force: force},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> removePackages(
    Iterable<_i6.PackageKitPackageId>? packageIds, {
    Set<_i6.PackageKitTransactionFlag>? transactionFlags = const {},
    bool? allowDeps = false,
    bool? autoremove = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePackages,
          [packageIds],
          {
            #transactionFlags: transactionFlags,
            #allowDeps: allowDeps,
            #autoremove: autoremove,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> resolve(
    Iterable<String>? packages, {
    Set<_i6.PackageKitTransactionFlag>? transactionFlags = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolve,
          [packages],
          {#transactionFlags: transactionFlags},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> searchFiles(
    Iterable<String>? values, {
    Set<_i6.PackageKitFilter>? filter = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFiles,
          [values],
          {#filter: filter},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> searchNames(
    Iterable<String>? values, {
    Set<_i6.PackageKitFilter>? filter = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchNames,
          [values],
          {#filter: filter},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> updatePackages(
    Iterable<_i6.PackageKitPackageId>? packageIds, {
    Set<_i6.PackageKitTransactionFlag>? transactionFlags = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePackages,
          [packageIds],
          {#transactionFlags: transactionFlags},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> upgradeSystem(
    String? distroId,
    _i6.PackageKitDistroUpgrade? upgradeKind, {
    Set<_i6.PackageKitTransactionFlag>? transactionFlags = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upgradeSystem,
          [
            distroId,
            upgradeKind,
          ],
          {#transactionFlags: transactionFlags},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
