include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - directives_ordering
    - prefer_relative_imports
    - prefer_single_quotes
    - type_annotate_public_apis
    - unawaited_futures
