// Mocks generated by Mockito 5.3.2 from annotations
// in software/test/services/package_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:file/file.dart' as _i8;
import 'package:file/local.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:packagekit/packagekit.dart' as _i2;
import 'package:software/package_state.dart' as _i6;
import 'package:software/services/package_service.dart' as _i3;
import 'package:software/store_app/common/packagekit/package_model.dart' as _i7;
import 'package:software/updates_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePackageKitPackageId_0 extends _i1.SmartFake
    implements _i2.PackageKitPackageId {
  _FakePackageKitPackageId_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PackageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackageService extends _i1.Mock implements _i3.PackageService {
  MockPackageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set lastRequireRestart(_i2.PackageKitRestart? _lastRequireRestart) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastRequireRestart,
          _lastRequireRestart,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set lastUpdatesPercentage(int? _lastUpdatesPercentage) => super.noSuchMethod(
        Invocation.setter(
          #lastUpdatesPercentage,
          _lastUpdatesPercentage,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set lastProcessedId(_i2.PackageKitPackageId? _lastProcessedId) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastProcessedId,
          _lastProcessedId,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set lastUpdatesState(_i4.UpdatesState? _lastUpdatesState) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastUpdatesState,
          _lastUpdatesState,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set lastInfo(_i2.PackageKitInfo? _lastInfo) => super.noSuchMethod(
        Invocation.setter(
          #lastInfo,
          _lastInfo,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<_i2.PackageKitPackageId> get updates => (super.noSuchMethod(
        Invocation.getter(#updates),
        returnValue: <_i2.PackageKitPackageId>[],
      ) as List<_i2.PackageKitPackageId>);
  @override
  _i5.Stream<bool> get updatesChanged => (super.noSuchMethod(
        Invocation.getter(#updatesChanged),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);
  @override
  List<_i2.PackageKitPackageId> get installedPackages => (super.noSuchMethod(
        Invocation.getter(#installedPackages),
        returnValue: <_i2.PackageKitPackageId>[],
      ) as List<_i2.PackageKitPackageId>);
  @override
  _i5.Stream<bool> get installedPackagesChanged => (super.noSuchMethod(
        Invocation.getter(#installedPackagesChanged),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);
  @override
  _i5.Stream<bool> get groupsChanged => (super.noSuchMethod(
        Invocation.getter(#groupsChanged),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);
  @override
  List<_i2.PackageKitRepositoryDetailEvent> get repos => (super.noSuchMethod(
        Invocation.getter(#repos),
        returnValue: <_i2.PackageKitRepositoryDetailEvent>[],
      ) as List<_i2.PackageKitRepositoryDetailEvent>);
  @override
  _i5.Stream<bool> get reposChanged => (super.noSuchMethod(
        Invocation.getter(#reposChanged),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);
  @override
  _i5.Stream<_i2.PackageKitRestart> get requireRestart => (super.noSuchMethod(
        Invocation.getter(#requireRestart),
        returnValue: _i5.Stream<_i2.PackageKitRestart>.empty(),
      ) as _i5.Stream<_i2.PackageKitRestart>);
  @override
  _i5.Stream<int?> get updatesPercentage => (super.noSuchMethod(
        Invocation.getter(#updatesPercentage),
        returnValue: _i5.Stream<int?>.empty(),
      ) as _i5.Stream<int?>);
  @override
  _i5.Stream<_i2.PackageKitPackageId?> get processedId => (super.noSuchMethod(
        Invocation.getter(#processedId),
        returnValue: _i5.Stream<_i2.PackageKitPackageId?>.empty(),
      ) as _i5.Stream<_i2.PackageKitPackageId?>);
  @override
  _i5.Stream<String> get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
        returnValue: _i5.Stream<String>.empty(),
      ) as _i5.Stream<String>);
  @override
  _i5.Stream<String> get manualRepoName => (super.noSuchMethod(
        Invocation.getter(#manualRepoName),
        returnValue: _i5.Stream<String>.empty(),
      ) as _i5.Stream<String>);
  @override
  _i5.Stream<_i4.UpdatesState> get updatesState => (super.noSuchMethod(
        Invocation.getter(#updatesState),
        returnValue: _i5.Stream<_i4.UpdatesState>.empty(),
      ) as _i5.Stream<_i4.UpdatesState>);
  @override
  _i5.Stream<_i2.PackageKitInfo?> get info => (super.noSuchMethod(
        Invocation.getter(#info),
        returnValue: _i5.Stream<_i2.PackageKitInfo?>.empty(),
      ) as _i5.Stream<_i2.PackageKitInfo?>);
  @override
  _i5.Stream<_i2.PackageKitStatus?> get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i5.Stream<_i2.PackageKitStatus?>.empty(),
      ) as _i5.Stream<_i2.PackageKitStatus?>);
  @override
  _i5.Stream<_i6.PackageState> get packageState => (super.noSuchMethod(
        Invocation.getter(#packageState),
        returnValue: _i5.Stream<_i6.PackageState>.empty(),
      ) as _i5.Stream<_i6.PackageState>);
  @override
  _i5.Stream<bool> get selectionChanged => (super.noSuchMethod(
        Invocation.getter(#selectionChanged),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);
  @override
  bool get allSelected => (super.noSuchMethod(
        Invocation.getter(#allSelected),
        returnValue: false,
      ) as bool);
  @override
  _i2.PackageKitPackageId getUpdate(int? index) => (super.noSuchMethod(
        Invocation.method(
          #getUpdate,
          [index],
        ),
        returnValue: _FakePackageKitPackageId_0(
          this,
          Invocation.method(
            #getUpdate,
            [index],
          ),
        ),
      ) as _i2.PackageKitPackageId);
  @override
  void setUpdatesChanged(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setUpdatesChanged,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.PackageKitPackageId? getInstalledId(String? name) =>
      (super.noSuchMethod(Invocation.method(
        #getInstalledId,
        [name],
      )) as _i2.PackageKitPackageId?);
  @override
  void setInstalledPackagesChanged(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setInstalledPackagesChanged,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setGroupsChanged(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setGroupsChanged,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setReposChanged(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setReposChanged,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.PackageKitGroup? getGroup(_i2.PackageKitPackageId? id) =>
      (super.noSuchMethod(Invocation.method(
        #getGroup,
        [id],
      )) as _i2.PackageKitGroup?);
  @override
  void setRequireRestart(_i2.PackageKitRestart? value) => super.noSuchMethod(
        Invocation.method(
          #setRequireRestart,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setUpdatePercentage(int? value) => super.noSuchMethod(
        Invocation.method(
          #setUpdatePercentage,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setProcessedId(_i2.PackageKitPackageId? value) => super.noSuchMethod(
        Invocation.method(
          #setProcessedId,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setErrorMessage(String? value) => super.noSuchMethod(
        Invocation.method(
          #setErrorMessage,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setManualRepoName(String? value) => super.noSuchMethod(
        Invocation.method(
          #setManualRepoName,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setUpdatesState(_i4.UpdatesState? value) => super.noSuchMethod(
        Invocation.method(
          #setUpdatesState,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setInfo(_i2.PackageKitInfo? value) => super.noSuchMethod(
        Invocation.method(
          #setInfo,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setStatus(_i2.PackageKitStatus? value) => super.noSuchMethod(
        Invocation.method(
          #setStatus,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setPackageState(_i6.PackageState? value) => super.noSuchMethod(
        Invocation.method(
          #setPackageState,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void selectAll() => super.noSuchMethod(
        Invocation.method(
          #selectAll,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void deselectAll() => super.noSuchMethod(
        Invocation.method(
          #deselectAll,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool isUpdateSelected(_i2.PackageKitPackageId? update) => (super.noSuchMethod(
        Invocation.method(
          #isUpdateSelected,
          [update],
        ),
        returnValue: false,
      ) as bool);
  @override
  void selectUpdate(
    _i2.PackageKitPackageId? id,
    bool? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #selectUpdate,
          [
            id,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> init({Set<_i2.PackageKitFilter>? filters = const {}}) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#filters: filters},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> refreshUpdates() => (super.noSuchMethod(
        Invocation.method(
          #refreshUpdates,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  void sendUpdateNotification({required String? updatesAvailable}) =>
      super.noSuchMethod(
        Invocation.method(
          #sendUpdateNotification,
          [],
          {#updatesAvailable: updatesAvailable},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<void> updateAll({
    required String? updatesComplete,
    required String? updatesAvailable,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAll,
          [],
          {
            #updatesComplete: updatesComplete,
            #updatesAvailable: updatesAvailable,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> getInstalledPackages(
          {Set<_i2.PackageKitFilter>? filters = const {
            _i2.PackageKitFilter.installed
          }}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInstalledPackages,
          [],
          {#filters: filters},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> remove({required _i7.PackageModel? model}) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
          {#model: model},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> install({required _i7.PackageModel? model}) =>
      (super.noSuchMethod(
        Invocation.method(
          #install,
          [],
          {#model: model},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> isInstalled({required _i7.PackageModel? model}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isInstalled,
          [],
          {#model: model},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> getDetails({required _i7.PackageModel? model}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetails,
          [],
          {#model: model},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> getUpdateDetail({required _i7.PackageModel? model}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpdateDetail,
          [],
          {#model: model},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> toggleRepo({
    required String? id,
    required bool? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleRepo,
          [],
          {
            #id: id,
            #value: value,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> addRepo(String? manualRepoName) => (super.noSuchMethod(
        Invocation.method(
          #addRepo,
          [manualRepoName],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<List<_i2.PackageKitPackageId>> findPackageKitPackageIds({
    required Iterable<String>? searchQuery,
    Set<_i2.PackageKitFilter>? filter = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findPackageKitPackageIds,
          [],
          {
            #searchQuery: searchQuery,
            #filter: filter,
          },
        ),
        returnValue: _i5.Future<List<_i2.PackageKitPackageId>>.value(
            <_i2.PackageKitPackageId>[]),
      ) as _i5.Future<List<_i2.PackageKitPackageId>>);
  @override
  _i5.Future<void> getDetailsAboutLocalPackage({
    required _i7.PackageModel? model,
    _i8.FileSystem? fileSystem = const _i9.LocalFileSystem(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailsAboutLocalPackage,
          [],
          {
            #model: model,
            #fileSystem: fileSystem,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> installLocalFile({
    required _i7.PackageModel? model,
    _i8.FileSystem? fileSystem = const _i9.LocalFileSystem(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #installLocalFile,
          [],
          {
            #model: model,
            #fileSystem: fileSystem,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  void reboot() => super.noSuchMethod(
        Invocation.method(
          #reboot,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
