name: snap-store
summary: App Center
description: App Center
confinement: strict
base: core22
grade: stable
version: git

parts:
  flutter-git:
    plugin: nil
    source: .
    override-build: |
      bash $CRAFT_PART_SRC/scripts/install-fvm.sh
      fvm install
      fvm flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - git
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ""

  snap-store:
    after: [flutter-git]
    source: .
    plugin: nil
    override-build: |
      set -eux
      fvm install
      fvm dart pub global activate melos

      set +e # ignore pub errors
      # when building locally artifacts can pollute the container and cause builds to fail
      # this helps increase reliability for local builds
      fvm dart pub global run melos clean
      fvm dart pub global run melos bootstrap
      set -e

      fvm dart pub global run melos exec -c 1 --fail-fast --depends-on=build_runner -- \
      fvm dart run build_runner build --delete-conflicting-outputs

      cd packages/app_center
      fvm flutter gen-l10n
      fvm flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

apps:
  snap-store:
    command: bin/snap-store
    environment: &store_env
      RATINGS_SERVICE_URL: '91.189.95.24'
      RATINGS_SERVICE_PORT: '443'
      RATINGS_SERVICE_USE_TLS: 'false'
    desktop: bin/data/flutter_assets/assets/app-center.desktop
    extensions: [gnome]
    plugs: &store_plugs
      - appstream-metadata
      - desktop
      - desktop-launch
      - network
      - snapd-control
      - packagekit-control

# This entry, along with the corresponding .desktop file, is required
# to allow Snapd Desktop Integration to open the Snap Center in the
# "updates" page when the user clicks "Show updates" in a notification.
# DO NOT DELETE.
  show-updates:
    command: bin/snap-store --updates
    desktop: bin/data/flutter_assets/assets/app-center-updates.desktop
    environment: *store_env
    extensions: [gnome]
    plugs: *store_plugs

slots:
  packagekit-svc:
    interface: dbus
    bus: session
    name: org.freedesktop.PackageKit
  dbus-name:
    interface: dbus
    bus: session
    name: io.snapcraft.Store
